=begin
#SDK API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

# Common files
require 'togglr-client/api_client'
require 'togglr-client/api_error'
require 'togglr-client/version'
require 'togglr-client/configuration'

# Models
require 'togglr-client/models/error'
require 'togglr-client/models/error_bad_request'
require 'togglr-client/models/error_error'
require 'togglr-client/models/error_internal_server_error'
require 'togglr-client/models/error_not_found'
require 'togglr-client/models/error_permission_denied'
require 'togglr-client/models/error_too_many_requests'
require 'togglr-client/models/error_unauthorized'
require 'togglr-client/models/evaluate_response'
require 'togglr-client/models/feature_error_report'
require 'togglr-client/models/feature_health'
require 'togglr-client/models/health_response'
require 'togglr-client/models/track_request'

# APIs
require 'togglr-client/api/default_api'

module TogglrClient
  class << self
    # Customize default settings for the SDK using block.
    #   TogglrClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
